const mongoose=require('mongoose')
const validator=require('validator')

const govtSchema=new mongoose.Schema({
    aadhar_main_id:{
		type:String
	},
	aadhar_main_url:{
		type:String
	},
	pan_main_id:{
		type:String
	},
	pan_main_url:{
		type:String
	},
	driving_license_main_id:{
		type:String
	},
	driving_license_main_url:{
		type:String
	},
	domicile_main_id:{
		type:String
	},
	domicile_main_url:{
		type:String
	},
    caste_main_id:{
		type:String
	},
	caste_main_url:{
		type:String
	},
    birth_main_id:{
		type:String
	},
	birth_main_url:{
		type:String
	},
    income_certificate_main_id:{
		type:String
	},
	income_certificate_main_url:{
		type:String
	},
    disabled_main_id:{
		type:String
	},
	disabled_main_url:{
		type:String
	},
    bike_registration_main_id:{
		type:String
	},
	bike_registration_main_url:{
		type:String
	},
    car_registration_main_id:{
		type:String
	},
	car_registration_main_url:{
		type:String
	},
    arm_license_main_id:{
		type:String
	},
	arm_license_main_url:{
		type:String
	},
    marriage_certificate_main_id:{
		type:String
	},
	marriage_certificate_main_url:{
		type:String
	},
    ration_card_main_id:{
		type:String
	},
	ration_card_main_url:{
		type:String
	},
    voter_id_main_id:{
		type:String
	},
	voter_id_main_url:{
		type:String
	},
    passport_main_id:{
		type:String
	},
	passport_main_url:{
		type:String
	},
	owner:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:'User'
    }
},{
    timestamps:true
})

const Govt=mongoose.model('Govt',govtSchema)

module.exports=Govt