const mongoose=require('mongoose')
const validator=require('validator')

const documentSchema=new mongoose.Schema({
    x_migration_main_id:{
		type:String
	},
	x_migration_main_url:{
		type:String
	},
	x_passing_main_id:{
		type:String
	},
	x_passing_main_url:{
		type:String
	},
	x_marksheet_main_id:{
		type:String
	},
	x_marksheet_main_url:{
		type:String
	},
	x_skill_main_id:{
		type:String
	},
	x_skill_main_url:{
		type:String
	},
	xii_migration_main_id:{
		type:String
	},
	xii_migration_main_url:{
		type:String
	},
	xii_passing_main_id:{
		type:String
	},
	xii_passing_main_url:{
		type:String
	},
	xii_marksheet_main_id:{
		type:String
	},
	xii_marksheet_main_url:{
		type:String
	},
	xii_skill_main_id:{
		type:String
	},
	xii_skill_main_url:{
		type:String
	},
	teacher_marksheet_main_id:{
		type:String
	},
	teacher_marksheet_main_url:{
		type:String
	},
	teacher_certificate_main_id:{
		type:String
	},
	teacher_certificate_main_url:{
		type:String
	},
	ug_main_id:{
		type:String
	},
	ug_main_url:{
		type:String
	},
	pg_main_id:{
		type:String
	},
	pg_main_url:{
		type:String
	},
	owner:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:'User'
    }
},{
    timestamps:true
})

const Document=mongoose.model('Document',documentSchema)

module.exports=Document